# Generated by Django 3.0.4 on 2021-11-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d', verbose_name='image')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=150, verbose_name='color_name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'color',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_product', models.CharField(max_length=50, verbose_name='size_product')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'size',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('heigth', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='heigth')),
                ('length', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='length')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='pvp')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='image')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='discount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Category', verbose_name='category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_raiting', models.IntegerField(default=0, verbose_name='product_raiting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='product_id')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ['id'],
            },
        ),
    ]
