# Generated by Django 4.0.1 on 2022-01-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_raiting',
            new_name='valoration_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.AddField(
            model_name='color',
            name='code_color',
            field=models.CharField(default='', max_length=8, verbose_name='code_color'),
        ),
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.CharField(default='', max_length=2000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='product.Color', verbose_name='color'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product.Size', verbose_name='sizes'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_product',
            field=models.CharField(max_length=80, verbose_name='size_product'),
        ),
    ]
