# Generated by Django 3.2.9 on 2022-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_tags_product_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.CharField(default='', max_length=2000, verbose_name='description'),
        ),
    ]
