# Generated by Django 3.2.9 on 2022-02-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('product', '0006_auto_20220219_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='supplier'),
        ),
    ]
