# Generated by Django 4.0.3 on 2022-03-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='last_color',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_color',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_color',
            field=models.CharField(default='', max_length=8),
        ),
    ]
