# Generated by Django 3.0.4 on 2021-11-06 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='description')),
            ],
            options={
                'verbose_name': 'StatusSend',
                'verbose_name_plural': 'StatusSends',
                'db_table': 'status_send',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatusSendSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_arrival', models.DateField(default=datetime.datetime.now, verbose_name='date_arrival')),
                ('delivered', models.BooleanField(default='delivered')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Sale', verbose_name='sale_id')),
                ('status_send', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status_send.StatusSend', verbose_name='status_send_id')),
            ],
            options={
                'verbose_name': 'StatusSendSale',
                'verbose_name_plural': 'StatusSendSales',
                'db_table': 'status_send_sale',
                'ordering': ['id'],
            },
        ),
    ]
