# Generated by Django 4.0.3 on 2022-05-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_remove_sale_warranty_id_detailsale_size'),
        ('status_send', '0003_alter_statussendsale_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statussendsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.sale', unique=True, verbose_name='sale_id'),
        ),
    ]
