# Generated by Django 4.0.3 on 2022-10-19 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_alter_detailsale_ammount_alter_detailsale_price_and_more'),
        ('status_send', '0004_alter_statussendsale_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statussend',
            name='description',
            field=models.CharField(max_length=180, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='statussendsale',
            name='date_actual_state',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha actualización envio'),
        ),
        migrations.AlterField(
            model_name='statussendsale',
            name='date_arrival',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha llegada'),
        ),
        migrations.AlterField(
            model_name='statussendsale',
            name='date_deliver_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha inicio envio'),
        ),
        migrations.AlterField(
            model_name='statussendsale',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='¿Entregada?'),
        ),
        migrations.AlterField(
            model_name='statussendsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.sale', unique=True, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='statussendsale',
            name='status_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status_send.statussend', verbose_name='Estado de envio'),
        ),
    ]
