# Generated by Django 4.0.3 on 2022-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyModeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emergency_actived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'EmergencyModeApp',
                'verbose_name_plural': 'EmergencyModeApp',
                'db_table': 'emergencymodeapp',
                'ordering': ['id'],
            },
        ),
    ]
