# Generated by Django 3.0.4 on 2021-11-06 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('covered_months', models.IntegerField(default=0, verbose_name='covered_months')),
            ],
            options={
                'verbose_name': 'Incidence',
                'verbose_name_plural': 'Incidences',
                'db_table': 'incidence',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeIncidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_type_incidence', models.CharField(max_length=150, verbose_name='name_incidence')),
            ],
            options={
                'verbose_name': 'TypeIncidence',
                'verbose_name_plural': 'TypeIncidences',
                'db_table': 'type_incidence',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='date_start')),
                ('date_end', models.DateField(default=datetime.datetime.now, verbose_name='date_end')),
            ],
            options={
                'verbose_name': 'WarrantyPurchase',
                'verbose_name_plural': 'WarrantyPurchases',
                'db_table': 'warranty_purchase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantySale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='date_start')),
                ('date_end', models.DateField(default=datetime.datetime.now, verbose_name='date_end')),
            ],
            options={
                'verbose_name': 'WarrantySale',
                'verbose_name_plural': 'WarrantySales',
                'db_table': 'warranty_sale',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyIncidenceSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty.Incidence', verbose_name='incidence_id')),
                ('warranty_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty.WarrantySale', verbose_name='warranty_sale_id')),
            ],
            options={
                'verbose_name': 'WarrantyIncidenceSale',
                'verbose_name_plural': 'WarrantyIncidenceSales',
                'db_table': 'warranty_incidence_sale',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyIncidencePurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty.Incidence', verbose_name='incidence_id')),
                ('warranty_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty.WarrantyPurchase', verbose_name='warranty_sale_id')),
            ],
            options={
                'verbose_name': 'WarrantyIncidencePurchase',
                'verbose_name_plural': 'WarrantyIncidencePurchases',
                'db_table': 'warranty_incidence_purchase',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='incidence',
            name='type_incidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty.TypeIncidence', verbose_name='type_incidence'),
        ),
    ]
