# Generated by Django 3.2.9 on 2022-02-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='covered_months',
        ),
        migrations.RemoveField(
            model_name='incidence',
            name='type_incidence',
        ),
        migrations.DeleteModel(
            name='TypeIncidence',
        ),
    ]
