# Generated by Django 3.2.9 on 2022-02-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_auto_20220210_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyincidencepurchase',
            name='incidence',
        ),
        migrations.AddField(
            model_name='warrantyincidencepurchase',
            name='incidence',
            field=models.ManyToManyField(to='warranty.Incidence', verbose_name='incidence_id'),
        ),
        migrations.RemoveField(
            model_name='warrantyincidencesale',
            name='incidence',
        ),
        migrations.AddField(
            model_name='warrantyincidencesale',
            name='incidence',
            field=models.ManyToManyField(to='warranty.Incidence', verbose_name='incidence_id'),
        ),
    ]
