# Generated by Django 3.2.9 on 2022-02-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_auto_20220210_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantypurchase',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='warrantypurchase',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='warrantysale',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='warrantysale',
            name='date_start',
        ),
        migrations.AddField(
            model_name='warrantypurchase',
            name='months_coverred',
            field=models.IntegerField(default=3, verbose_name='months_covered'),
        ),
        migrations.AddField(
            model_name='warrantysale',
            name='months_coverred',
            field=models.IntegerField(default=3, verbose_name='months_covered'),
        ),
    ]
