# Generated by Django 3.2.9 on 2022-02-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_auto_20220210_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyincidencesale',
            name='incidence',
        ),
        migrations.RemoveField(
            model_name='warrantyincidencesale',
            name='warranty_sale',
        ),
        migrations.AddField(
            model_name='warrantypurchase',
            name='incidence',
            field=models.ManyToManyField(to='warranty.Incidence', verbose_name='incidence_id'),
        ),
        migrations.AddField(
            model_name='warrantysale',
            name='incidence',
            field=models.ManyToManyField(to='warranty.Incidence', verbose_name='incidence_id'),
        ),
        migrations.DeleteModel(
            name='WarrantyIncidencePurchase',
        ),
        migrations.DeleteModel(
            name='WarrantyIncidenceSale',
        ),
    ]
