# Generated by Django 3.2.9 on 2022-03-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0005_auto_20220210_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='name_incidence'),
        ),
    ]
