# Generated by Django 4.0.3 on 2022-04-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0006_incidence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warrantypurchase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warrantysale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
