# Generated by Django 4.0.3 on 2022-04-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_colors_product_last_color_and_more'),
        ('warranty', '0008_warrantyproduct_warrantysale_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warrantyproduct',
            options={'ordering': ['id'], 'verbose_name': 'WarrantyProduct', 'verbose_name_plural': 'WarrantyProduct'},
        ),
        migrations.AddField(
            model_name='warrantyproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='warrantyproduct',
            name='warranty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warranty.warrantysale'),
        ),
        migrations.AlterModelTable(
            name='warrantyproduct',
            table='warranty_product',
        ),
    ]
