# Generated by Django 4.0.3 on 2022-04-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_purchase_warranty_id'),
        ('warranty', '0009_alter_warrantyproduct_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarrantyPurchase',
        ),
    ]
