# Generated by Django 4.0.3 on 2022-10-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_description_alter_category_image_and_more'),
        ('warranty', '0011_alter_warrantyproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', unique=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='warrantyproduct',
            name='warranty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warranty.warrantysale', verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='warrantysale',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='warrantysale',
            name='incidence',
            field=models.ManyToManyField(to='warranty.incidence', verbose_name='Incidencia'),
        ),
        migrations.AlterField(
            model_name='warrantysale',
            name='months_coverred',
            field=models.IntegerField(default=3, verbose_name='Meses cubiertos'),
        ),
        migrations.AlterField(
            model_name='warrantysale',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Nombre'),
        ),
    ]
