# Generated by Django 3.0.4 on 2021-11-06 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('ammount', models.IntegerField(default=0, verbose_name='ammount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='subtotal')),
            ],
            options={
                'verbose_name': 'DetailSale',
                'verbose_name_plural': 'DetailSales',
                'db_table': 'detail_sale',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_sale', models.DateField(default=datetime.datetime.now, verbose_name='date_sale')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='iva')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='iva')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sale',
                'ordering': ['id'],
            },
        ),
    ]
