# Generated by Django 3.0.4 on 2021-11-06 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_comment_user'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='detailsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='product_id'),
        ),
        migrations.AddField(
            model_name='detailsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Sale', verbose_name='sale_id'),
        ),
    ]
