# Generated by Django 3.2.9 on 2022-02-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0005_auto_20220210_0348'),
        ('sale', '0002_auto_20211106_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='warranty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warranty.warrantysale', verbose_name='warranty_sale'),
        ),
    ]
