# Generated by Django 4.0.3 on 2022-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_detailsale_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=3, verbose_name='iva'),
        ),
    ]
