# Generated by Django 4.0.3 on 2022-05-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_colors_product_last_color_and_more'),
        ('sale', '0005_alter_sale_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='warranty_id',
        ),
        migrations.AddField(
            model_name='detailsale',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.size', verbose_name='size_id'),
        ),
    ]
