# Generated by Django 4.0.3 on 2022-06-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email'),
        ('sale', '0006_remove_sale_warranty_id_detailsale_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.directionuser', verbose_name='direction_id'),
        ),
    ]
