# Generated by Django 4.0.3 on 2022-07-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_sale_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(default=True, verbose_name='Esta pagada?'),
        ),
    ]
