# Generated by Django 4.0.3 on 2022-10-19 04:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_directionuser_exterior_number_and_more'),
        ('product', '0009_alter_category_description_alter_category_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0008_sale_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsale',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.sale', verbose_name='Numero factura'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.size', verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='detailsale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.directionuser', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
