# Generated by Django 4.0.3 on 2022-04-22 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(blank=True, max_length=150, verbose_name='direction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DirectionUser',
                'verbose_name_plural': 'DirectionUsers',
                'db_table': 'directionuser',
                'ordering': ['id'],
            },
        ),
    ]
