# Generated by Django 4.0.3 on 2022-06-02 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionuser',
            name='direction',
        ),
        migrations.AddField(
            model_name='directionuser',
            name='exterior_number',
            field=models.CharField(default='', max_length=15, verbose_name='exterior_number'),
        ),
        migrations.AddField(
            model_name='directionuser',
            name='interior_number',
            field=models.CharField(default='', max_length=15, verbose_name='interior_number'),
        ),
        migrations.AddField(
            model_name='directionuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='direction'),
        ),
        migrations.AddField(
            model_name='directionuser',
            name='postal_code',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='postal_code'),
        ),
        migrations.AddField(
            model_name='directionuser',
            name='street',
            field=models.CharField(blank=True, max_length=80, verbose_name='street'),
        ),
    ]
