# Generated by Django 4.0.3 on 2022-06-02 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_directionuser_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionuser',
            name='exterior_number',
            field=models.CharField(default='', max_length=15, verbose_name='Numero exterior'),
        ),
        migrations.AlterField(
            model_name='directionuser',
            name='interior_number',
            field=models.CharField(default='', max_length=15, verbose_name='Numero interior'),
        ),
        migrations.AlterField(
            model_name='directionuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='directionuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='nombre direccion'),
        ),
        migrations.AlterField(
            model_name='directionuser',
            name='postal_code',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='directionuser',
            name='street',
            field=models.CharField(blank=True, max_length=80, verbose_name='calle'),
        ),
    ]
