# Generated by Django 3.2.9 on 2022-02-19 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_auto_20220219_1956'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_purchase', models.DateField(default=datetime.datetime.now, verbose_name='date_sale')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='iva')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='iva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='supplier_id')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('ammount', models.IntegerField(default=0, verbose_name='ammount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='product_id')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase', verbose_name='purchase_id')),
            ],
            options={
                'verbose_name': 'DetailPurchase',
                'verbose_name_plural': 'DetailPurchase',
                'db_table': 'detail_purchase',
                'ordering': ['id'],
            },
        ),
    ]
