# Generated by Django 4.0.3 on 2022-05-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_colors_product_last_color_and_more'),
        ('purchase', '0004_remove_purchase_supplier_alter_purchase_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpurchase',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.size', verbose_name='size_id'),
        ),
    ]
