# Generated by Django 4.0.3 on 2022-05-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_detailpurchase_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpurchase',
            name='color',
            field=models.CharField(default='', max_length=8),
        ),
    ]
