# Generated by Django 4.0.3 on 2022-10-19 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_description_alter_category_image_and_more'),
        ('purchase', '0006_detailpurchase_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpurchase',
            name='ammount',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detailpurchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detailpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detailpurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase', verbose_name='Número factura'),
        ),
        migrations.AlterField(
            model_name='detailpurchase',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.size', verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='detailpurchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchase',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha factura'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=3, verbose_name='Iva'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total'),
        ),
    ]
