# Generated by Django 4.0.3 on 2022-04-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_ammount_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ammount_size',
        ),
        migrations.RemoveField(
            model_name='stockproductsize',
            name='product',
        ),
        migrations.AddField(
            model_name='stockproductsize',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.stock', verbose_name='stock'),
        ),
    ]
