# Generated by Django 4.0.3 on 2022-07-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_protection_database', models.CharField(default='', max_length=512, verbose_name='Estado proteccion')),
            ],
            options={
                'verbose_name': 'SelfProtection',
                'verbose_name_plural': 'SelfProtection',
                'db_table': 'selfprotection',
                'ordering': ['id'],
            },
        ),
    ]
