# Generated by Django 4.0.3 on 2022-07-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_selfprotection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelfProtection',
        ),
    ]
