# Generated by Django 4.0.3 on 2022-10-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_selfprotection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareplication',
            name='autoreplication',
            field=models.BooleanField(default=True, verbose_name='Autoreplicación'),
        ),
    ]
